In [72]:
import pandas as pd
import csv

file_path = 'H://file csv//th5.csv'

# Mở file với mã hóa 'utf-8' và bỏ qua các lỗi mã hóa
with open(file_path, mode='r', encoding='utf-8', errors='replace') as file:
    content = file.read()

# Lưu nội dung vào một file tạm thời
temp_path = 'temp_file.csv'
with open(temp_path, mode='w', encoding='utf-8') as temp_file:
    temp_file.write(content)

# Đọc file tạm thời vào dataframe
df = pd.read_csv(temp_path)


# print ten cac cot
print(df.columns)

Index(['__time', '/cf_1/pose/header/header/stamp',
       '/cf_1/pose/pose/orientation/pitch', '/cf_1/pose/pose/orientation/roll',
       '/cf_1/pose/pose/orientation/w', '/cf_1/pose/pose/orientation/x',
       '/cf_1/pose/pose/orientation/y', '/cf_1/pose/pose/orientation/yaw',
       '/cf_1/pose/pose/orientation/z', '/cf_1/pose/pose/position/x',
       '/cf_1/pose/pose/position/y', '/cf_1/pose/pose/position/z',
       '/cf_2/pose/header/header/stamp', '/cf_2/pose/pose/orientation/pitch',
       '/cf_2/pose/pose/orientation/roll', '/cf_2/pose/pose/orientation/w',
       '/cf_2/pose/pose/orientation/x', '/cf_2/pose/pose/orientation/y',
       '/cf_2/pose/pose/orientation/yaw', '/cf_2/pose/pose/orientation/z',
       '/cf_2/pose/pose/position/x', '/cf_2/pose/pose/position/y',
       '/cf_2/pose/pose/position/z', '/cf_3/pose/header/header/stamp',
       '/cf_3/pose/pose/orientation/pitch', '/cf_3/pose/pose/orientation/roll',
       '/cf_3/pose/pose/orientation/w', '/cf_3/pose/pose/orientation/x',
       '/cf_3/pose/pose/orientation/y', '/cf_3/pose/pose/orientation/yaw',
       '/cf_3/pose/pose/orientation/z', '/cf_3/pose/pose/position/x',
       '/cf_3/pose/pose/position/y', '/cf_3/pose/pose/position/z',
       '/cf_4/pose/header/header/stamp', '/cf_4/pose/pose/orientation/pitch',
       '/cf_4/pose/pose/orientation/roll', '/cf_4/pose/pose/orientation/w',
       '/cf_4/pose/pose/orientation/x', '/cf_4/pose/pose/orientation/y',
       '/cf_4/pose/pose/orientation/yaw', '/cf_4/pose/pose/orientation/z',
       '/cf_4/pose/pose/position/x', '/cf_4/pose/pose/position/y',
       '/cf_4/pose/pose/position/z'],
      dtype='object')

In [82]:
columns_to_select = [
                    # '/cf_1/pose/pose/position/x', 
                    # '/cf_1/pose/pose/position/y', 
                    # '/cf_1/pose/pose/position/z'
                    # '/cf_2/pose/pose/position/x', 
                    # '/cf_2/pose/pose/position/y', 
                    # '/cf_2/pose/pose/position/z' 
                    # '/cf_3/pose/pose/position/x', 
                    # '/cf_3/pose/pose/position/y', 
                    # '/cf_3/pose/pose/position/z'
                    '/cf_4/pose/pose/position/x',
                    '/cf_4/pose/pose/position/y',
                    '/cf_4/pose/pose/position/z'
                     ]

df_selected = df[columns_to_select]
print(df_selected.head(5))

   /cf_4/pose/pose/position/x  /cf_4/pose/pose/position/y  \
0                         NaN                         NaN
1                    0.999357                    1.001446
2                         NaN                         NaN
3                         NaN                         NaN
4                         NaN                         NaN

   /cf_4/pose/pose/position/z
0                         NaN
1                    0.997608
2                         NaN
3                         NaN
4                         NaN

In [83]:
df_selected.dropna(inplace=False)

,/cf_4/pose/pose/position/x,/cf_4/pose/pose/position/y,/cf_4/pose/pose/position/z
1,0.999357,1.001446,0.997608
5,0.999363,1.001466,0.997631
9,0.999379,1.001477,0.997660
13,0.999387,1.001490,0.997672
17,0.999382,1.001513,0.997668
...,...,...,...
1433840,-0.120997,2.030278,3.008330
1433844,-0.136519,2.027982,3.008873
1433849,-0.152256,2.025352,3.009221
1433853,-0.167628,2.022517,3.009456
1433856,-0.181452,2.019578,3.009647

In [84]:
# write to csv
df_selected.dropna().to_csv('H://file csv//th54.csv', index=False)